### ISSUE TITLE
Suppress output from %get and %put

### ISSUE THREAD

**Issue by dabbatelli** [vatlab/sos-javascript#2]
Currently, %get and %put magics create outputs with the value of the variables being passed.
Under some circumstances (passwords, or just long very values) this might not be the desired behavior.

Small example below:
![firefox_saMlbd3abC](https://user-images.githubusercontent.com/13344050/82156432-4983df80-987b-11ea-8de5-6c69558c3f0f.png)

Is there a way to suppress this output?
I have tried playing around with the %capture magic (which seems to be the standard way to suppress outputs in a notebook) but with no luck.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/82223147-e8462580-98e7-11ea-8a97-039b3bd6c5a0.png)

OK, I can confirm this bug. `sos-javascript` got less attention as you can see the number of tickets here. Let me see if there is an easy fix.

**Comment by BoPeng** [comment]
Note that you do not have to use `%use` magic which is usually used for more advanced usages. Selecting language from the dropdown box is usually enough.

**Comment by BoPeng** [comment]
I have fixed the bug and released sos-javascript 0.18.1
