### ISSUE TITLE
Complete tests for individual datatypes

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-javascript#3]
https://github.com/vatlab/sos-javascript/blob/master/test/test_data_exchange.py is not completed yet. We will need to go through each datatypes and make sure they work as expected.

**Comment by joannfeng** [comment]
I'm a bit lost on how to test this code, as commands I used previously are not working. Do I need to install iJavaScript kernel?

**Comment by BoPeng** [comment]
This ticket is intended to let you learn unit testing. You will need to set up a SoS environment with iJavaScript kernel, the latest or master version of `sos-javascript`, then run

```
pytest
```
or more likely
```
pytest test_data_exchange.py::TestDataExchange::test_whatever
```
for individual tests. 

The latter part of the commented code is the previous tests that combined different types, and the middle commented part are tests that were copied from `sos-julia` and need to be adapted to `sos-javascript`. You essentially need to list types at the Python and JavaScript sides, and write `get` and `put` tests for each of them, as shown by the existing tests. It would be helpful for you to test the features in a JupyterLab session before adding the test code to `test_data_exchange.py`.

**Comment by BoPeng** [comment]
After it is done, it will be a good idea to update https://vatlab.github.io/sos-docs/doc/user_guide/sos_javascript.html with what you leant.
