### ISSUE TITLE
sos_notebook/kernel.py:837: RuntimeWarning: coroutine 'sos_JavaScript.get_vars' was never awaited

### ISSUE THREAD

**Issue by nibheis** [vatlab/sos-javascript#8]
Hi!

We've updated our jupyterlab/sos installation with the following module versions:

```
jupyterlab                    3.6.5
jupyterlab-sos                0.9.0
sos                           0.24.1
sos-bash                      0.21.0
sos-javascript                0.20.0
sos-matlab                    0.20.2
sos-notebook                  0.24.2
sos-papermill                 0.2.1
sos-python                    0.20.0
sos-r                         0.20.1
```

... and we have notice one blocking issue.

This cell:
```
%use SoS
%put my_var --to JavaScript
```
gives the following warning:
```
/opt/jlab-env/lib/python3.11/site-packages/sos_notebook/kernel.py:837: RuntimeWarning: coroutine 'sos_JavaScript.get_vars' was never awaited
  get_vars_func(items)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback 
```
and `my_vars` is not exported back to the Javascript subkernel (transfer from JavaScript to SoS works).

I changed the file `sos_javascript/kernel.py` and removed the `async` keyword in front of the `get_vars(...)` method and now it works (i.e. no more warning and variable is transferred).

However, I am not sure about this change, since `sos_r/kernel.py` also has an `async get_vars(...)` and I don't see any warning when using it.

What's the proper way of fixing this?

**Comment by BoPeng** [comment]
This is caused by an upstream change. I have fixed other language modules and somehow missed this one. Let me have a look at this this weekend.

**Comment by nibheis** [comment]
Hi @BoPeng!

Did you have a chance to look at this?
If it's trivial, can you please point me to other language modules that were fixed so that I can make the change myself and do a PR?

**Comment by BoPeng** [comment]
Sorry that I was not able to keep my promise, but this will be the first thing I look at this weekend.

**Comment by BoPeng** [comment]
Please update sos-notebook to version 0.24.3 and let me know if the problem persists.

**Comment by nibheis** [comment]
Hi @BoPeng !
I ran some basic tests and I am happy to confirm that it now works as expected.

**Comment by nibheis** [comment]
Thanks a lot for the quick fix!!

**Comment by BoPeng** [comment]
Glad that it works. Still struggling with JLab 4.x support though. Hopefully I can get it done today.
